apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
  namespace: slot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: slot.appp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 3000