apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-bazelgrpc
  namespace: bazelgrpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-bazelgrpc
  template:
    metadata:
      labels:
        app: gateway-bazelgrpc
    spec:
      containers:
        - name: gateway-bazelgrpc
          image: 534378753229.dkr.ecr.us-east-2.amazonaws.com/gateway-bazeldemo:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
